global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - rules/*.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093

scrape_configs:
  # Prometheus itself
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  # LI-FI Services
  - job_name: lifi-services
    static_configs:
      - targets:
          - localhost:8080
          # Skaffold RPC
      - targets:
          - localhost:7080
          # Coder
      - targets:
          - localhost:5900
          # WayVNC
    metrics_path: /metrics
    scrape_interval: 10s

  # Docker containers
  - job_name: docker
    static_configs:
      - targets:
          - localhost:9323
          # Docker daemon metrics

  # Node exporter for system metrics
  - job_name: node
    static_configs:
      - targets:
          - localhost:9100

  # Custom LI-FI metrics
  - job_name: lifi-custom
    static_configs:
      - targets:
          - localhost:5050
          # Web UI metrics
    metrics_path: /metrics
    scrape_interval: 30s

  # Flash script monitoring
  - job_name: flash-scripts
    static_configs:
      - targets:
          - localhost:8081
          # Flash script metrics endpoint
    metrics_path: /metrics
    scrape_interval: 60s